exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('rental').del()
    .then(function () {
      // Inserts seed entries
      // perhaps should add dates rented so users can specify the dates they need and only rentable properties are shown
      return knex('rental').insert([
        {
          id: 1,
          renter_id: 2,
          title: "Luxurious apartment, great location",
          location: "Brooklyn Brdige",
          type: 1,
          country: "USA",
          state: "NY",
          city: "Brooklyn",
          street_address: "140 Grove St",
          zip: 11221,
          bedrooms: 2,
          beds: 2,
          baths: 1,
          // no zip given --> we will need zip for coordinates as well as to validate existence
          guests: 4,
          description: "A nice, third story apartment building with a beautiful view of the city",
          featuredImg: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.LPQ86MK4lwyIVWaclZouOQHaE7%26pid%3DApi&f=1",
        },
        {
          id: 2,
          renter_id: 2,
          title: "Roomy, Private House on the outskirts of the city",
          location: "Times Square",
          type: 2,
          country: "USA",
          state: "NY",
          city: "New York",
          street_address: "420 E 51st St",
          zip: 10022,
          bedrooms: 4,
          beds: 4,
          baths: 2.5,
          guests: 6,
          description: "This is a large house with a private back yard, great for BBQs or just enjoying the weather",
          featuredImg: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fstatic01.nyt.com%2Fimages%2F2017%2F01%2F08%2Frealestate%2F08SELLING-BIG%2F08SELLING-BIG-videoSixteenByNineJumbo1600.jpg&f=1&nofb=1",
        },
        {
          id: 3,
          renter_id: 2,
          title: "Unique experience",
          location: "Empire State Building",
          type: 3,
          country: "USA",
          state: "NY",
          city: "New York",
          street_address: "125 87th St",
          zip: 10128,
          bedrooms: 1,
          beds: 1,
          baths: 1,
          guests: 2,
          description: "Not sure what a secondary space is, but that's what you're getting!",
          featuredImg: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.pinimg.com%2Foriginals%2F95%2Fe2%2F06%2F95e206c8904587736afe57edc1c9695b.jpg&f=1&nofb=1",
        },
        {
          id: 4,
          renter_id: 2,
          title: "A unique experience you're likely not to forget",
          location: "Vander Ende - Onderdonk House Museum",
          type: 4,
          country: "USA",
          state: "NY",
          city: "Ridgewood",
          street_address: "2017 Palmetto St",
          zip: 11385,
          bedrooms: 2,
          beds: 2,
          baths: 1,
          guests: 4,
          description: "Once an art studio, now a unique place to stay right in the middle of town. If you like high ceilings, this is your place",
          featuredImg: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Flivinator.com%2Fwp-content%2Fuploads%2F2016%2F05%2Fshedbuilt.jpg&f=1&nofb=1",
        },
        {
          id: 5,
          renter_id: 2,
          title: "Friendly, romantic bed and breakfast",
          location: "Prospect Park",
          type: 5,
          country: "USA",
          state: "NY",
          city: "Brooklyn",
          street_address: "82 Pierrepont St",
          zip: 11201,
          bedrooms: 1,
          beds: 1,
          baths: 1,
          guests: 2,
          description: "If you like the smell of coffee and pancakes in the morning, this is your home away from home",
          featuredImg: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.srE4YKshbNAoAMTfYL8y5gHaEu%26pid%3DApi&f=1",
        }
      ]);
    });
};
